### ISSUE TITLE
running for loop over all output and inputs

### ISSUE THREAD

**Issue by MeY0u** [hideakitai/PCA95x5#10]
hello,
thank you for creating this library.
unfortunately i ran into a problem from a library i downloaded from Arduio ide.
in the example for output you declared for (size_t i = 0: i <16 ; i++)
 when using this example receive:

invalid conversion from 'size_t' {aka 'unsigned int'} to 'PCA95x5::Port::Port' [-fpermissive]
       ioex.write(i,PCA95x5::Level::H);

can idea how to make it work without using static_cast?

**Comment by hideakitai** [comment]
Already fixed in v0.1.3

https://github.com/hideakitai/PCA95x5/issues/8

**Comment by hideakitai** [comment]
Please see a new example.

https://github.com/hideakitai/PCA95x5/blob/main/examples/output/output.ino

**Comment by MeY0u** [comment]
yes.... its not so practical way around. isnt enum creates a uint value? so when passing an argument it should point to the correct location.

**Comment by MeY0u** [comment]
also, how many ports does read() actually reads? because it uses Reg::INPUT_PORT_0 only.

**Comment by hideakitai** [comment]
`read()` reads all ports. `read(port)` reads one port.

```c++
uint16_t read();
Level::Level read(const uint8_t port);
```

> yes.... its not so practical way around. isnt enum creates a uint value? so when passing an argument it should point to the correct location.

I couldn't understand what you wanted to say, but feel free to make a pull request.

**Comment by MeY0u** [comment]
> `read()` reads all ports. `read(port)` reads one port.
> 
> ```c++
> uint16_t read();
> Level::Level read(const uint8_t port);
> ```
> 
> > yes.... its not so practical way around. isnt enum creates a uint value? so when passing an argument it should point to the correct location.
> 
> I couldn't understand what you wanted to say, but feel free to make a pull request.

you wrote your code very cleaver but i cant pass uint or size value to functions that waits to receive argument of the type enum. this makes working with the code harder than it could be. even with your example you used "static_cast<PCA95x5::Port::Port>(uint_8t value) " to make the write function work.
is there a chance you make it more easy to access? you are the master mind behind this beauty.

**Comment by hideakitai** [comment]
> i cant pass uint or size value to functions that waits to receive argument of the type enum. 

Yes. It’s a protection not to use the wrong port from the user. For example, uint 7 is for P07, but uint 8 is for P10, and uint 9 is for P11.

> this makes working with the code harder than it could be. even with your example you used "static_castPCA95x5::Port::Port(uint_8t value) " to make the write function work.

I don’t think casting unit is “hard”. It is a warning for the user not to use the wrong value for it.

> is there a chance you make it more easy to access? you are the master mind behind this beauty.

As I said above, casting is not “hard” and is required only when you use a unit to write ports. Please pass the port name if you want to write one port.
