### ISSUE TITLE
API call when used as attach(wire, 0x21) doesn't works from the example file.

### ISSUE THREAD

**Issue by ZillKhan** [hideakitai/PCA95x5#12]
Hello,
Hope you are doing well.
I am trying to use both the buses and creating 2 instances to use both addresses 0x20 and 0x21 but unfortunately, I think you have set the value static in your library. 
Here:

`static constexpr uint8_t BASE_I2C_ADDR = 0x20;`
    
public:
    void attach(WireType& wire, uint8_t i2c_addr = BASE_I2C_ADDR) {
        this->wire = &wire;
        this->addr = i2c_addr;
    }
    
Is this possible to make this function a bit dynamic so that the user can pass the i2c address from the main.ino file?

**Comment by hideakitai** [comment]
As you pasted, `attach()` accepts variable `i2c_addr`. `uint8_t i2c_addr = BASE_I2C_ADDR` means that "use `BASE_I2C_ADDR` if not I2C address is passed to this function".

https://github.com/hideakitai/PCA95x5/blob/8b854a832e9cb98fa1fba6c145768696560658f2/PCA95x5.h#L77-L80

So `attach(Wire)` uses `BASE_I2C_ADDR` and `attach(Wire, 0x21)` uses `0x21` as i2c addr. Could you try the two devices individually to see if communication is possible?

**Comment by ZillKhan** [comment]
It worked individually but when I tried this it didn't work.

`#include <PCA95x5.h>

PCA9555 PCA_BUS1;   // Set PCA_BUS1 to 0x20
PCA9555 PCA_BUS2;   // Set PCA_BUS2 to 0x21

void setup() {
    Serial.begin(115200);
    delay(2000);

    Wire.begin(32, 33);

    // Initialization for PCA_BUS1
    PCA_BUS1.attach(Wire, 0x20);
    PCA_BUS1.polarity(PCA95x5::Polarity::ORIGINAL_ALL);
    PCA_BUS1.direction(PCA95x5::Direction::OUT_ALL);
    PCA_BUS1.write(PCA95x5::Level::L_ALL);  // Set all ports low initially

    // Initialization for PCA_BUS2
    PCA_BUS2.attach(Wire, 0x21);
    PCA_BUS2.polarity(PCA95x5::Polarity::ORIGINAL_ALL);
    PCA_BUS2.direction(PCA95x5::Direction::OUT_ALL);
    PCA_BUS2.write(PCA95x5::Level::L_ALL);  // Set all ports low initially
}

void loop() {
    // For PCA_BUS1
    Serial.println("Set port P00 high (PCA_BUS1)");
    PCA_BUS1.write(PCA95x5::Port::P00, PCA95x5::Level::H);  // Set P00 high for PCA_BUS1
    delay(2000);

    Serial.println("Set port P00 low (PCA_BUS1)");
    PCA_BUS1.write(PCA95x5::Port::P00, PCA95x5::Level::L);  // Set P00 low for PCA_BUS1
    delay(2000);

    // For PCA_BUS2
    Serial.println("Set port P00 high (PCA_BUS2)");
    PCA_BUS2.write(PCA95x5::Port::P00, PCA95x5::Level::H);  // Set P00 high for PCA_BUS2
    delay(2000);

    Serial.println("Set port P00 low (PCA_BUS2)");
    PCA_BUS2.write(PCA95x5::Port::P00, PCA95x5::Level::L);  // Set P00 low for PCA_BUS2
    delay(2000);
}`

**Comment by hideakitai** [comment]
What “didn’t work” mean? Could you let me know more details?

**Comment by hideakitai** [comment]
If you still need help, please reopen this issue.
