### ISSUE TITLE
How to address multiple PCA9535 ?

### ISSUE THREAD

**Issue by m1larepa** [hideakitai/PCA95x5#13]
By looking supplied examples and reading library .h, I don't understand how to address multiple PCA95x5, at other addresses than default 0x20 .
I have four devices at 0x20, 0x21, 0x22 and 0x23 I would like to control attached to ESP (8266 or 32).
Can you help ?
Best regards,
M1larepa.

**Comment by hideakitai** [comment]
You can n do it by

```cpp
ioex.attach(Wire, 0x21);
```

**Comment by hideakitai** [comment]
If you still need help, please feel free to reopen this issue.
