### ISSUE TITLE
Only can read from half the inputs

### ISSUE THREAD

**Issue by AlexWard** [hideakitai/PCA95x5#14]
Hello, I am just using your base example input code on Arduino IDE with an Arduino Mega with an I2C address of 0x20 on the chip PCA9555.
I can read the inputs for pins  0,3,4,5,12,13,14,15 but not for 1,2,6,7,8,9,10,11
Seems strange that it is exactly half of them and not one complete set from port 0 OR port 1.
Could you please advise if there is something I am missing in the configuration.
Let me know if you need me to post some code.
Thanks, Alex.

**Comment by AlexWard** [comment]
Additionally, I have two other PCA9555 on I2C Addresses 0x21 and 0x22 and both work on all pins as outputs.

**Comment by AlexWard** [comment]
It does show a read value of 1 for ALL pins with original polarity and all the pins change to 0 when inverted. It just does not change if the input is grounded like the working pins listed.

**Comment by hideakitai** [comment]
Could you give me your code?

**Comment by AlexWard** [comment]
//SETUP I/O READER FOR 16X INPUTS
#include <PCA95x5.h>

PCA9555 inputs;
PCA9555 outputs1;
PCA9555 outputs2;

void setup() {

Serial.begin(115200);
  Serial.println("Program Begin");
  
// Sets up I2C addresses for input and output cards
  Wire.begin();
  uint8_t i2c_addri = 0x20;
  inputs.attach(Wire, i2c_addri);
  inputs.polarity(PCA95x5::Polarity::INVERTED_ALL);
  inputs.direction(PCA95x5::Direction::IN_ALL);

  uint8_t i2c_addr1 = 0x21;
  outputs1.attach(Wire, i2c_addr1);
  outputs1.polarity(PCA95x5::Polarity::ORIGINAL_ALL);
  outputs1.direction(PCA95x5::Direction::OUT_ALL);
  outputs1.direction(12, PCA95x5::Direction::IN);
  outputs1.direction(13, PCA95x5::Direction::IN);
  outputs1.direction(14, PCA95x5::Direction::IN);
  outputs1.direction(15, PCA95x5::Direction::IN);
  outputs1.write(PCA95x5::Level::L_ALL);

  uint8_t i2c_addr2 = 0x22;
  outputs2.attach(Wire, i2c_addr2);
  outputs2.polarity(PCA95x5::Polarity::ORIGINAL_ALL);
  outputs2.direction(PCA95x5::Direction::OUT_ALL);
  outputs2.direction(12, PCA95x5::Direction::IN);
  outputs2.direction(13, PCA95x5::Direction::IN);
  outputs2.direction(14, PCA95x5::Direction::IN);
  outputs2.direction(15, PCA95x5::Direction::IN);
  outputs2.write(PCA95x5::Level::L_ALL);
}

void loop() {
  

 for (size_t i = 0; i < 8; ++i) {
    Serial.print("out 1 set port high: ");
    Serial.println(i);
    Serial.print("\t");
    outputs1.write(i, PCA95x5::Level::H);
    Serial.print(outputs1.read(i), BIN);
    delay(5);
  }
  delay(2000);

  for (size_t i = 0; i < 8; ++i) {
    Serial.print("out 1 set port low: ");
    Serial.println(i);
    Serial.print("\t");
    outputs1.write(i, PCA95x5::Level::L);
    Serial.print(outputs1.read(i), BIN);
    delay(5);
  }
  Serial.println("");

  //Serial.print("Inputs x16 ");
  //Serial.println(inputs.read(), BIN); // change number in brackets to only read 1 pin
  //delay (5);
  Serial.print("Input 0 = ");
  Serial.println(inputs.read(0), BIN); // Input 0 working
  delay (5);
  Serial.print("Input 1 = ");
  Serial.println(inputs.read(1), BIN); // Input 1 not working
   
  delay (5);
  Serial.print("Input 2 = ");
  Serial.println(inputs.read(2), BIN); // Input 2 not working
 
  delay (5);
  Serial.print("Input 3 = ");
  Serial.println(inputs.read(3), BIN); // Input 3 working
  delay (5);
  Serial.print("Input 4 = ");
  Serial.println(inputs.read(4), BIN); // Input 4 working
  delay (5);
  Serial.print("Input 5 = ");
  Serial.println(inputs.read(5), BIN); // Input 5 working
  delay (5);
  Serial.print("Input 6 = ");
  Serial.println(inputs.read(6), BIN); // Input 6 not working
  delay (5);
  Serial.print("Input 7 = ");
  Serial.println(inputs.read(7), BIN); // Input 7 not working
  delay (5);
  Serial.print("Input 8 = ");
  Serial.println(inputs.read(8), BIN); // Input 8 not working
  delay (5);
  Serial.print("Input 9 = ");
  Serial.println(inputs.read(9), BIN); // Input 9 not working
  delay (5);
  Serial.print("Input 10 = ");
  Serial.println(inputs.read(10), BIN); // Input 10 not working
  delay (5);
  Serial.print("Input 11 = ");
  Serial.println(inputs.read(11), BIN); // Input 11 not working
  delay (5);
  Serial.print("Input 12 = ");
  Serial.println(inputs.read(12), BIN); // Input 12 working
  delay (5);
  Serial.print("Input 13 = ");
  Serial.println(inputs.read(13), BIN); // Input 13 working
  delay (5);
  Serial.print("Input 14 = ");
  Serial.println(inputs.read(14), BIN); // Input 14 working
  delay (5);
  Serial.print("Input 15 = ");
  Serial.println(inputs.read(15), BIN); // Input 15 working
  

/*  Serial.print("DIAG1 1/2 Outputs1 ");
  Serial.println(outputs1.read(12), BIN);
  Serial.print("DIAG1 3/4 Outputs1 ");
  Serial.println(outputs1.read(13), BIN);
  Serial.print("DIAG2 1/2 Outputs1 ");
  Serial.println(outputs1.read(14), BIN);
  Serial.print("DIAG2 3/4 Outputs1 ");
  Serial.println(outputs1.read(15), BIN);
  Serial.print("DIAG1 1/2 Outputs2 ");
  Serial.println(outputs2.read(12), BIN);
  Serial.print("DIAG1 3/4 Outputs2 ");
  Serial.println(outputs2.read(13), BIN);
  Serial.print("DIAG2 1/2 Outputs2 ");
  Serial.println(outputs2.read(14), BIN);
  Serial.print("DIAG2 3/4 Outputs2 ");
  Serial.println(outputs2.read(15), BIN);
*/

  for (size_t i = 0; i < 8; ++i) {
    Serial.print("out 2 set port high: ");
    Serial.println(i);
    Serial.print("\t");
    outputs2.write(i, PCA95x5::Level::H);
    Serial.print(outputs2.read(i), BIN);
    delay(5);
  }
  delay(2000);
  for (size_t i = 0; i < 8; ++i) {
    Serial.print("out 2 set port low: ");
    Serial.println(i);
    Serial.print("\t");
    outputs2.write(i, PCA95x5::Level::L);
    Serial.print(outputs2.read(i), BIN);
    delay(5);
  }

delay(30000); // will be triggered on interupt in final program.
}

**Comment by AlexWard** [comment]
My appologies, it all works perfectly, I have a PCB issue. Thankyou for your time and sorry to bother you. Thanks, Alex.

**Comment by AlexWard** [comment]
Complete
