### ISSUE TITLE
Feauture request: Recieve state of the port or bank.

### ISSUE THREAD

**Issue by admindotnu** [hideakitai/PCA95x5#2]
Feauture request: Recieve state of the port or bank.

The PCA9535 for example can easyly glitch with some minor overvoltage. En extra command to recieve the state of the banks (inputs / outputs) it is easy to  check if settings are still in place. If not, settings can be pushed before port commands.

**Comment by hideakitai** [comment]
Hi, sorry for the late reply. Do you mean adding a feature to read if the port/bank is input or output?

**Comment by hideakitai** [comment]
Currently, there's no plan for this. If you still need help, please feel free to reopen this issue.
