### ISSUE TITLE
please add example to config each pin of the expander individualy

### ISSUE THREAD

**Issue by SpaceTeddy** [hideakitai/PCA95x5#3]
for instance:

pin 0 is input
pin 8 is output low
pin 9 is output high
....

is it?:
tca9555.direction(PCA95x5::Port::P00, PCA95x5::Direction::IN);

tca9555.direction(PCA95x5::Port::P08, PCA95x5::Direction::OUT);
tca9555.write(PCA95x5::Port::P02, PCA95x5::Level::L);

tca9555.direction(PCA95x5::Port::P09, PCA95x5::Direction::OUT);
tca9555.write(PCA95x5::Port::P03, PCA95x5::Level::H);

thx

**Comment by hideakitai** [comment]
Yes. Please use these APIs

```cpp
Level::Level read(const uint8_t port);
bool write(const uint8_t port, const Level::Level level);
bool polarity(const uint8_t port, const Polarity::Polarity pol);
bool direction(const uint8_t port, const Direction::Direction dir);
```
